### PR TITLE
Fix Chrome support and add the field to send BiDi commands

### LINKED ISSUE #11: Add a way to send BiDi commands
This could be as simple as an input on the BiDi panel we'll add in #10 
Or we could tweak the console input to accept BiDi commands, maybe prefixing commands with `:bidi <command>` or something similar

### PR DESCRIPTION
**Pull request by lutien**
Closes #11

### CODE REVIEW

**Comment by whimboo** [comment]
@juliandescottes would we need similar fixes for your client to get it connected to Chrome again? Or did we already land those? I cannot remember and didn't try out Chrome for a while.

**Comment by lutien** [comment]
> @juliandescottes would we need similar fixes for your client to get it connected to Chrome again? Or did we already land those? I cannot remember and didn't try out Chrome for a while.

I've just checked the Julian's client with Chrome, and it seems to be working fine.

File: src/components/App.js [hunk 1]
```diff
@@ -366,6 +367,16 @@ class App extends React.Component {
...
   };
 
+  sendCommand = (e) => {
+    e.preventDefault();
+    try {
+      const commandObject = JSON.parse(this.state.bidiCommand);
+      this.#client.sendCommand(commandObject.method, commandObject.params);
+    } catch (e) {
+      console.log({ e });
+    }
```
Comment (juliandescottes) [inline src/components/App.js]: nit: let's use a different error variable name to avoid shadowing the e parameter from the surrounding function.

I would also console.error instead of log. When you submit an invalid message, the only user feedback we have at the moment is the devtools' console panel, so let's make it visible.
```suggestion
    } catch (error) {
      console.error({ error });
    }
```

File: src/components/BiDCommandInput.js [hunk 2]
```diff
@@ -0,0 +1,23 @@
+import React from "react";
+
+import "./BiDCommandInput.css";
```
Comment (juliandescottes) [inline src/components/BiDCommandInput.js]:
```suggestion
import "./BiDiCommandInput.css";
```
Small typo in the filenames for this component (js & css)

File: src/components/BiDiLog.js [hunk 3]
```diff
@@ -1,14 +1,20 @@
...
       <ul className="bidi-log__list">
-        {log.map((entry) => (
-          <BiDiLogEntry entry={entry} key={entry.message}/>
+        <BiDCommandInput
+          onInputChange={onBidiCommandChange}
+          onSubmit={sendCommand}
+          value={bidiCommand}
+        />
+        {log.toReversed().map((entry) => (
+          <BiDiLogEntry entry={entry} key={entry.message} />
```
Comment (juliandescottes) [inline src/components/BiDiLog.js]: Not related to your change, but in my BiDi logs I had twice the message `WebSocket closed` and therefore they both had the same key. Because of this each re-render of the component leads to a react error, and since we re-render on every keystroke (due to the state update for inputChange), this makes the console logs hard to use.

**Review by juliandescottes — APPROVED** [review]
Thanks! Some nits + suggestion for a quick follow up.

File: src/components/App.js (hunk 1 above)
Comment (lutien) [reply src/components/App.js]: Sure, updated ✅

File: src/components/BiDiLog.js (hunk 3 above)
Comment (lutien) [reply src/components/BiDiLog.js]: Right, I've added the index to the message, so it should make it more unique
